#collections
#list->mutablr-changable
lst=[1,3.5,'hai',3]
print(len(lst))
print(lst[:-1])
print(lst[::-1])
print(lst[1:4])
print(lst[:])
lst[0]=6
print(lst)
lst.append('hello')
print(lst)
lst.extend([8,9])
print(lst)
lst.insert(5,4)
print(lst)
lst.pop()
print(lst)
lst.pop(3)
print(lst)
lst.remove(6)
print(lst)
lst1=[1,34,54,3,6]
lst1.sort()
print(lst1)
lst1.sort(reverse=True)
print(lst1)
lst1.reverse()
print(lst1)
print(max(lst1))
print(min(lst1))
list=[1,2,3,[4,5,[7,8]],6]
print(list[3][2][0])
print(list[3][1])